### PR TITLE
added project popup nebular tag

### PR DESCRIPTION
**Pull request by tonae-patterson**

### CODE REVIEW

**Review by dyl10s — CHANGES_REQUESTED** [review]
Working well, just 2 smaller things. I think maybe if there was some helper text that said like `press enter to add tag` next to the label would be nice, also for some reason when the popup comes up the first thing that is in focus is the Tags input. I am not sure why the browser defaults to that.

**Review by dyl10s — CHANGES_REQUESTED** [review]
I can no longer select the tag input

**Comment by tonae-patterson** [comment]
Fixed the input focus to make the first form input of priority. Whoever tests pls this let me know if you get any console errors.

**Comment by dyl10s** [comment]
> Fixed the input focus to make the first form input of priority. Whoever tests pls this let me know if you get any console errors.

Didn't get any errors on my end

**Review by dyl10s — CHANGES_REQUESTED** [review]
After entering the Client name, I press tab to go to the next item and it does not move to the Project Name input, I think this has to do with setting the tabindex to 9999

**Review by dyl10s — APPROVED** [review]

**Pull request merged**
