### PR TITLE
user profile design

### LINKED ISSUE #12: User Profile Design
Design user profile page:

- Edit Name
- Projects assigned to
- Hours tracked (placeholder)

Admin/Professor View:

- Edit Name
- View All Projects
- All Hours tracked (placeholder)

### PR DESCRIPTION
**Pull request by tonae-patterson**
desktop side menu moves with scroll, but not desired. To be corrected

### CODE REVIEW

**Review by dyl10s — CHANGES_REQUESTED** [review]
A few things here that I see.

- Remove the sidebar. I don't think we need any of the other tabs.
- The page should be at its own route and not be a component of every screen. Maybe `/Profile`?
- The change password section should have an area for the user to add the new item they want to change. `Current Password`, `New Password`, `Verify New Password` maybe?
- Make the page full screen with the same background as the login / register pages
- If you had a plan for it I'm fine with it but what is the Cancel button there for? 

This is me just looking at things from a visual standpoint. I think @adamchlebek will take a look at the code.

**Comment by tonae-patterson** [comment]
- sidebar removed.
- page has its own route.
- password section corrected.
- page screen and background modified correctly.
- cancel button removed (error).

**Review by dyl10s — CHANGES_REQUESTED** [review]
I believe this component is actually going to be a page the user navigates to, similar to login or register. I think the route should be something smaller as well as the component moved to a different folder name as this is not really a shared component. Maybe `app\dashboard\pages`? I also feel like the new password fields should mimic the layout of the basic info area with a label and then a smaller textbox, that's just me though this is more a design question not really you must do it how I want 😊.  Also, I feel like the white background should be removed still to make it seem like a complete page.

**Comment by tonae-patterson** [comment]
I see what you were saying about the background. All set, I misunderstood you the first time. Also conflicts should be resolved.

**Review by dyl10s — CHANGES_REQUESTED** [review]
Alright, just a few more tweaks and I think it's good. I think we can move the update info button into the same section as the basic info because that's the information it's updating and it may be confusing from a user's point of view what the button does at the bottom of the page. Also, the change password button is now the same color as the background.

**Comment by tonae-patterson** [comment]
Good point, I'll be more observant to details like that. Update button moved and change password button is no longer background color

**Review by adamchlebek — APPROVED** [review]

**Review by adamchlebek — APPROVED** [review]

**Review by dyl10s — APPROVED** [review]

**Review by dyl10s — CHANGES_REQUESTED** [review]
Verifying that the merge went ok

**Review by dyl10s — APPROVED** [review]

**Pull request merged**
