### PR TITLE
added help params and more messages

### PR DESCRIPTION
**Pull request by tonae-patterson**

### CODE REVIEW

**Review by dyl10s — COMMENTED** [review]
Is it possible to use the Summary decorators for the parameters just like we do for the commands to dynamically create the help messages? 
image

**Comment by tonae-patterson** [comment]
I may have overthought this one, but if you literally just meant to update the params to match the above that works!

**Comment by jwaltt55** [comment]
Looks like there's a couple warnings that should probably be cleaned up (you can see em under the "Files Changed" tab). Also, do we want to keep the !say command or was that just for testing?

**Comment by tonae-patterson** [comment]
Weird the say command was still there i deleted that

**Comment by jwaltt55** [comment]
It looks like there's a duplicate line for !help:

cap

**Comment by jwaltt55** [comment]
I think we probably don't need to say "via discord" anywhere in the help commands. Since the users will be on Discord while using the bot, it's just something that we probably don't have to mention.

This is pretty nitpicky, but since we're focused on polish this sprint, we probably wanna have the apostrophes for words like "don't" and "user's".

The !stop command will prompt a user to select a timer to stop if multiple timers are present, instead of just stopping the most recently started timer like the current !help-timer command says.

For the !help-auth command, I think the wording for the !login section should be reworked a little, it seemed a bit hard to understand while I was reading through it.

**Review by jwaltt55 — APPROVED** [review]

**Pull request merged**
